# Generated by Django 5.1.5 on 2025-03-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory',
            field=models.IntegerField(choices=[(128, 'Base 128'), (256, 'Standart 256'), (512, 'Large 512'), (1024, 'Extreme 1024')]),
        ),
    ]
